"""add_platform_connection_id_to_conversations

Revision ID: 1cd564bfc1aa
Revises: 97271c88dc63
Create Date: 2026-05-18 00:23:12.507528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd564bfc1aa'
down_revision: Union[str, Sequence[str], None] = '97271c88dc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('platform_connection_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('external_user_id', sa.String(length=100), nullable=True))
    op.alter_column('conversations', 'whatsapp_number_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'wa_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_conversations_external_user_id'), 'conversations', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_platform_connection_id'), 'conversations', ['platform_connection_id'], unique=False)
    op.create_index(op.f('ix_conversations_wa_user_id'), 'conversations', ['wa_user_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'platform_connections', ['platform_connection_id'], ['id'])
    op.add_column('messages', sa.Column('platform_connection_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('external_user_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('external_message_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('platform', sa.String(length=30), nullable=True))
    op.alter_column('messages', 'whatsapp_number_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'wa_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_messages_external_message_id'), 'messages', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_messages_external_user_id'), 'messages', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_messages_platform'), 'messages', ['platform'], unique=False)
    op.create_index(op.f('ix_messages_platform_connection_id'), 'messages', ['platform_connection_id'], unique=False)
    op.create_index(op.f('ix_messages_wa_user_id'), 'messages', ['wa_user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'platform_connections', ['platform_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_wa_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform_connection_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_message_id'), table_name='messages')
    op.alter_column('messages', 'wa_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('messages', 'whatsapp_number_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'platform')
    op.drop_column('messages', 'external_message_id')
    op.drop_column('messages', 'external_user_id')
    op.drop_column('messages', 'platform_connection_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_wa_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_platform_connection_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_external_user_id'), table_name='conversations')
    op.alter_column('conversations', 'wa_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('conversations', 'whatsapp_number_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('conversations', 'external_user_id')
    op.drop_column('conversations', 'platform_connection_id')
    # ### end Alembic commands ###
