"""add_platform_connections

Revision ID: 97271c88dc63
Revises: 9cfd5cb2e8d3
Create Date: 2026-05-15 19:25:33.405107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97271c88dc63'
down_revision: Union[str, Sequence[str], None] = '9cfd5cb2e8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('platform_type', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_connections_platform_type'), 'platform_connections', ['platform_type'], unique=False)
    op.create_index(op.f('ix_platform_connections_status'), 'platform_connections', ['status'], unique=False)
    op.create_index(op.f('ix_platform_connections_tenant_id'), 'platform_connections', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_connections_tenant_id'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_status'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_platform_type'), table_name='platform_connections')
    op.drop_table('platform_connections')
    # ### end Alembic commands ###
