/**
 * Shared plan constants — single source of truth for plan labels, prices and
 * AI-response caps.
 *
 * Import from this module instead of defining inline constants.
 */

export const PLAN_LABELS: Record<string, string> = {
  trial: "Prueba",
  basic: "Básico",
  professional: "Profesional",
  enterprise: "Empresarial",
};

/**
 * AI-response cap copy per plan (owner-validated, marketing wording). The cap
 * unit is "respuestas con IA" — outbound messages generated by the LLM
 * (origin='ai') per tenant per month. FAQ (programadas) y escalaciones a un
 * asesor NO consumen el cupo. Trial = 3 días con IA; todas las menciones usan
 * tuteo.
 */
export const PLAN_AI_CAPS: Record<string, string> = {
  trial: "3 días con IA incluida (hasta 500 respuestas IA)",
  basic: "Hasta 2.000 respuestas con IA al mes",
  professional: "10.000 respuestas IA/mes y hasta 5 números de WhatsApp",
  enterprise: "Hasta 100.000 respuestas con IA al mes",
};

/**
 * Note shown under the plan table (owner-validated copy). Explains the cap
 * unit and what does NOT consume it.
 */
export const AI_QUOTA_NOTE =
  "1 respuesta con IA = 1 mensaje generado por IA. Al agotar tu cupo mensual, el bot continúa atendiendo con respuestas programadas (FAQ) para que no pierdas clientes. Las escalaciones a un asesor no consumen tu cupo.";

/**
 * Footnote under the plan table — the conversation estimate assumption.
 * Owner-validated: divide by ~4 messages per conversation, use "~" not "=".
 */
export const CONVERSATION_ESTIMATE_NOTE =
  "Cantidad estimada de conversaciones, asumiendo ~4 respuestas por conversación.";

/**
 * Escenario A (owner-validated, plan-differentiation): prices are pure copy
 * strings — never runtime arithmetic. Canon format is "$X.XXX/mes + IVA"
 * (dot-separated thousands, no "K" suffix) — matches agents/templates.py and
 * the web format "$699.900". The anti-undercut floor is $390.000: no SaaS
 * pricing surface may show less, and paid tiers always carry "+ IVA".
 * Corporate is intentionally absent: it is a marketing-only plan ("A cotizar")
 * and MUST NOT be payable/activatable in the payment flow.
 */
export const PRICE_LABELS: Record<string, string> = {
  basic: "Desde $390.000/mes + IVA",
  professional: "Desde $790.000/mes + IVA",
  enterprise: "Desde $1.590.000/mes + IVA",
};
